name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v2024.2
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      with:
        args: "--fail-threshold,0,--baseline,.github/workflows/qodana.sarif.json"     
    - name: Github code scanning  
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json